# This is a basic workflow to help you get started with Actions

name: Deploy to AWS Lambda

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "workflow"
  workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1 # 버지니아 북부
      AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}

    # Skip running release workflow on forks
    if: github.repository_owner == 'k1m743hyun'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      
      # Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Configure AWS credentials from Test account
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Make a Zip File
      - name: Make a Zip File
        run: zip -r ${{ github.event.repository.name }}.zip .

      # Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
          --function-name ${{ github.event.repository.name }} \
          --zip-file fileb://${{ github.event.repository.name }}.zip
          
      # Publish AWS Lambda
      - name: Publish AWS Lambda and Add alias
        run: |
          aws lambda publish-version \
          --description "Version published for Lambda@Edge" \
          --function-name ${{ github.event.repository.name }} > lam_conf.json;
          cat lam_conf.json
          
      # Get a CloudFront Configuration
      - name: Get CloudFront Configuration
        run: |
          aws cloudfront get-distribution-config \
          --id ${{ env.AWS_CLOUDFRONT_ID }} > cf_config.json;
          cat cf_config.json
          
      # Modify CloudFront Configuration
      - name: Modify CloudFront Configuration
        run: |
          version=$(cat lam_conf.json | jq '.Version | tonumber');
          echo "AWS Lambda version: $version";
          jq '.DistributionConfig.DefaultCacheBehavior.LambdaFunctionAssociations.Items[0].LambdaFunctionARN = "arn:aws:lambda:us-east-1:" + '\"${{ secrets.AWS_IAM }}\"' + ":function:" + '\"${{ github.event.repository.name }}\"' + ":"  + '\"$version\"' | del(.ETag) | .[]' cf_config.json > cf_config_modified.json;

        # cloudfront는 lambda alias로 연결할 수 없다.
        # aws lambda create-alias \
        # --function-name ${{ github.event.repository.name }} \
        # --function-version $version \

      # Update a CloudFront Configuration
      - name: Update a CloudFront Configuration
        run: |
          etag=$(cat cf_config.json | jq -r '.ETag');
          echo "etag: $etag";
          aws cloudfront update-distribution \
          --id ${{ env.AWS_CLOUDFRONT_ID }} \
          --if-match $etag \
          --distribution-config file://cf_config_modified.json 
